/* solutions.c */

#include "solutions.h"

void multiples_3_and_5() {

	/* local variables */
	int i, sum;

	printf("%s\n", "Multiples of 3 and 5");
	printf("%s\n", "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.");
	printf("%s\n", "");

	sum = 0;

	for (i = 1; i < 1000; i++) {
		if (i % 3 == 0 || i % 5 == 0) {
			sum += i;
		}
	}

	printf("%s%d\n", "The sum of multiples of 3 and 5 under 1000 is: ", sum);
	printf("%s\n", "Confirmed correct on Project Euler.");
	printf("%s\n", "");
}

void even_fibonacci_numbers() {

	/* local variables */
	int curr, prev, pprev, sum;

	printf("%s\n", "Even Fibonacci numbers");
	printf("%s%s%s\n", "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:",
		"1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...",
		"By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.");
	printf("%s\n", "");

	sum = 0;
	prev = 0; 
	pprev = 0;
	curr = 1;

	while(curr < 4000000) {
		pprev = prev;
		prev = curr;
		curr = prev + pprev;

		if (curr % 2 == 0)
			sum += curr;
	}

	printf("%s%d\n", "The sum of even Fibonacci numbers under 4 million is: ", sum);
	printf("%s\n", "Confirmed correct on Project Euler.");
	printf("%s\n", "");
}	