/* project_euler.c */

#include "project_euler.h"

int main(void) {

	/* local variables */
	int input;

	printf("%s\n", "");
	printf("%s\n", "Welcome to Tom's Project Euler solutions!");
	print_directory();

	input = -1;

	while (input != 0){

		/* menu */
		printf("%s\n", "");
		printf("%s\n", "Please select from the following solutions:");
		printf("%s\n", "1 - Multiples of 3 and 5");
		printf("%s\n", "2 - Even Fibonacci numbers");
		printf("%s\n", "3 - Largest Prime factor");
		printf("%s\n", "4 - Largest palindrome product");
		printf("%s\n", "5 - Smallest multiple");
		printf("%s\n", "6 - Sum square difference");
		printf("%s\n", "7 - 10001st prime");
		printf("%s\n", "8 - Largest product in a series");
		/*printf("%s\n", "9 - Special Pythagorean triplet");
		printf("%s\n", "10 - Summation of primes");
		printf("%s\n", "11 - Largest product in a grid");
		printf("%s\n", "12 - Highly divisible triangular number");*/
		printf("%s\n", "0 - Exit");

		get_input(&input);

		solutions(input);
	}

	return 0;
}

void solutions(int menuChoice) {

	switch (menuChoice) {
		case 1:
			problem_1();
			break;
		case 2:
			problem_2();
			break;
		case 3:
			problem_3();
			break;
		case 4:
			problem_4();
			break;
		case 5:
			problem_5();
			break;
		case 6:
			problem_6();
			break;
		case 7:
			problem_7();
			break;
		case 8:
			problem_8();
			break;
		case 0:
			break;	
		default:
			printf("%s\n", "Solution not yet implemented.");
			break;
	}
}

void problem_1() {

	/* local variables */
	int a, b, limit, input;
	
	a = 0;
	b = 0;
	limit = 0;
	input = 0;

	/* print title and problem */
	printf("%s\n", "Sum the multiples of two numbers.");
	printf("%s%s\n", "If we list all the natural numbers below 10 that are multiples", 
		"of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23."); 
	printf("%s\n", "The Project Euler problem is: find the sum of all the multiples of 3 or 5 below 1000.");
	printf("\n");

	printf("%s", "If you would like to see the Project Euler solution, press 0, press 1 to enter your own: ");
	get_input(&input);
	printf("\n");

	if (input == 0) {
		a = 3;
		b = 5;
		limit = 1000;
	} else {
		printf("%s", "Enter first number to sum: ");
		get_input(&a);

		printf("%s", "Enter second number to sum: ");
		get_input(&b);

		printf("%s", "Enter limit for multiples: ");
		get_input(&limit);
	}

	/* print result */
	printf("The sum of multiples of %d and %d under %d is %d.\n", 
		a,
		b, 
		limit, 
		sum_multiples(a, b, limit));

	printf("%s\n", "Confirmed correct on Project Euler.");
	printf("\n");
}

void problem_2() {
	
	/* local variables */
	int input, limit;

	/* print title and problem */
	printf("%s\n", "Even Fibonacci numbers");
	printf("%s\n%s\n%s\n", "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:",
		"1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...",
		"By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.");
	printf("\n");
	
	printf("%s", "If you would like to see the Project Euler solution, press 0, press 1 to enter your own: ");
	get_input(&input);
	printf("\n");

	if (input == 0) {
		limit = 4000000;
	} else {
		printf("%s", "Enter limit for Fibonacci sum: ");
		get_input(&limit);
	}

	/* print result */
	printf("The sum of even Fibonacci numbers under %d is: %d\n", limit, even_fibonacci_numbers(limit));
	printf("%s\n", "Confirmed correct on Project Euler.");
	printf("%s\n", "");
}

void problem_3() {

	/* local variables */
	int input;
	long long int limit;

	/* print title and problem */
	printf("%s\n", "Largest Prime factor");
	printf("%s\n%s\n", "The prime factors of 13195 are 5, 7, 13 and 29.",
		"What is the largest prime factor of the number 600851475143?");
	
	printf("%s", "If you would like to see the Project Euler solution, press 0, press 1 to enter your own: ");
	get_input(&input);
	printf("\n");

	if (input == 0) {
		limit = 600851475143;
	} else {
		printf("%s", "Enter the number you'd like to know the largest prime factor of: ");
		get_input_ll(&limit);
	}

	/* print result */
	printf("%s%d\n", "The largest prime factor of 600851475143 is:", largest_prime_factor(limit));
	printf("%s\n", "Confirmed correct on Project Euler.");
	printf("%s\n", "");	
}

void problem_4() {

	/* print title and problem */
	printf("%s\n", "Largest palindrome product");
	printf("%s\n%s\n%s\n", "A palindromic number reads the same both ways.",
		"The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 * 99.",
		"Find the largest palindrome made from the product of two 3-digit numbers.");
	printf("%s\n", "");

	/* print result */
	printf("%s%d\n", "The largest palimdromic product of two 3 digit numbers is: ", largest_palindrome_product());
	printf("%s\n", "Confirmed correct on Project Euler.");
	printf("%s\n", "");
}

void problem_5() {
	
}

void problem_6() {
	
}

void problem_7() {
	
}

void problem_8() {
	
}